version: '3.3'
services:
  mysql:
    image: mariadb
    restart: always
    volumes:
      - mariadb-data
      - ./mysql/backup:/tmp/mysql/backup
    environment:
      - "MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD"
      - "MYSQL_DATABASE=$MYSQL_DATABASE"
      - "MYSQL_USER=$MYSQL_USER"
      - "MYSQL_PASSWORD=$MYSQL_PASSWORD"
  mariadb-data:
    image: mariadb
    volumes:
      - ./volumes/mysql:/var/lib/mysql
      - "/etc/localtime:/etc/localtime:ro"
    command: /bin/true
  wordpress:
    image: wordpress
    restart: always
    volumes:
      - wpdata
    ports:
      - "80:80"
      - "443:443"
    environment:
      - "WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD"
    links:
      - mysql
  cadvisor:
    image: google/cadvisor
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:rw"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
    ports:
      - "8080:8080"